gan_params: 
 latent_size : 256
 image_size : 64

training_params: 
 data_dir : "./screenshots/train"
 epochs : 150
 lr : 0.00001
 batch_size : 8
 log_interval : 10
 stats : [[0.5, 0.5, 0.5], [0.5, 0.5, 0.5]]
 